version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin
  MYSQL_DATABASE: mdb
  REACT_APP_SERVER_PORT: 8000
  MONGO_USERNAME: root
  MONGO_PASSWORD: root
  MONGO_HOSTNAME: localhost
  MONGO_PORT: 27017
  MONGO_DB: mdb

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/mdb.sql:/docker-entrypoint-initdb.d/mdb.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongodb
    restart: unless-stopped
    environment:
      <<: *common-variables
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mysql
      - mongo
    command: npm start
  # client:
  #   build: ./client
  #   environment:
  #     <<: *common-variables
  #     NODE_PATH: src
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client/src:/app/src
  #   links:
  #     - server
  #   stdin_open: true
  #   command: npm start
volumes:
  dbdata: